[deps]
ContinuousWavelets = "96eb917e-2868-4417-9cb6-27e7ff17528f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FourierFilterFlux = "3d7dfd45-6c90-4c9b-b697-194a05757159"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ScatteringPlots = "196eb918-4f6f-4958-a9e4-adbde22f279d"
ScatteringTransform = "eadaac29-8b6b-5395-80fd-9ce36bb46293"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
